version: '3.8'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: jobify
      POSTGRES_USER: jobify_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobify_user -d jobify"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql+asyncpg://jobify_user:${POSTGRES_PASSWORD}@database:5432/jobify
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REMOTIVE_BASE: https://remotive.com/api
      FRONTEND_URL: https://jobify-frontend-rho.vercel.app
      CORS_ORIGINS: '["https://jobify-frontend-rho.vercel.app"]'
      DEBUG: false
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8080"
    restart: unless-stopped

volumes:
  postgres_data: